name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    strategy:
      matrix:
        node-version: [ '14.x', '16.x', '18.x', '19.x' ]
        # TODO: Windows will fail tests- even if every test passed.
        # os: [ ubuntu-latest, windows-latest ]
        os: [ ubuntu-latest ]
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2.2.4
      with:
        version: 7
    
    - name: Use NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: pnpm
      
    - name: Install dependencies
      run: pnpm install

    - name: Build project
      run: pnpm build

    - name: Test project
      run: pnpm vitest --run --no-threads