name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    strategy:
      matrix:
        node-version: [ '14.x', '16.x', '18.x', '19.x' ]
        # node-version: [ '16.x', '18.x', '19.x' ]
        os: [ ubuntu-latest, windows-latest ]
        # os: [ ubuntu-latest ]
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: npm
      
    - name: Install dependencies
      run: npm run install

    - name: Build project
      run: npm run build

    - name: Test project
      run: npm run test