name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    strategy:
      matrix:
        node-version: [ '16.x', '18.x', '19.x' ]
        os: [ ubuntu-latest, windows-latest ]
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2.2.4
      with:
        run_install: true
    
    - name: Use NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: pnpm

    - name: Build project
      run: pnpm run build

    - name: Test project
      run: pnpm run coverage